# PR Labeler configuration - automatically label PRs based on file changes

# Documentation
documentation:
  - '**/*.md'
  - 'docs/**/*'
  - 'wiki/**/*'

# GitHub Actions
github-actions:
  - '.github/workflows/**/*'
  - '.github/actions/**/*'

# Dependencies
dependencies:
  - 'package.json'
  - 'package-lock.json'
  - 'yarn.lock'
  - 'pnpm-lock.yaml'

# JavaScript
javascript:
  - '**/*.js'
  - '**/*.mjs'
  - '**/*.cjs'

# Configuration
config:
  - '**/*.json'
  - '**/*.yml'
  - '**/*.yaml'
  - '**/*.toml'
  - '.gitignore'
  - '.gitattributes'

# Tests
test:
  - '**/*.test.js'
  - '**/*.spec.js'
  - 'test/**/*'
  - 'tests/**/*'

# CI/CD
ci:
  - '.github/**/*'
  - '.gitlab-ci.yml'
  - '.circleci/**/*'
  - 'azure-pipelines.yml'

# Security
security:
  - 'SECURITY.md'
  - '.github/workflows/codeql.yml'
  - '.github/workflows/secret-scanning.yml'
  - '.gitleaks.toml'

# Bot-related
bot:
  - '.github/dependabot.yml'
  - '.github/renovate.json'
  - '.github/mergify.yml'
  - '.all-contributorsrc'
