const globals = require('globals');

module.exports = [
    {
        ignores: [
            'docs/**',
            'node_modules/**',
            'coverage/**',
            'dist/**',
            '.circleci/**',
            '.github/**',
            'dashboard/.next/**',
            'dashboard/node_modules/**',
        ],
    },
    {
        languageOptions: {
            globals: {
                ...globals.node,
                Game: 'readonly',
                Memory: 'readonly',
                Room: 'readonly',
                Structure: 'readonly',
                Creep: 'readonly',
                StructureContainer: 'readonly',
                StructureSpawn: 'readonly',
                StructureController: 'readonly',
                StructureTower: 'readonly',
                StructureExtension: 'readonly',
                StructureLink: 'readonly',
                FIND_SOURCES: 'readonly',
                FIND_STRUCTURES: 'readonly',
                FIND_MY_STRUCTURES: 'readonly',
                FIND_CONSTRUCTION_SITES: 'readonly',
                FIND_MY_CREEPS: 'readonly',
                FIND_MY_SPAWNS: 'readonly',
                FIND_HOSTILE_CREEPS: 'readonly',
                STRUCTURE_SPAWN: 'readonly',
                STRUCTURE_EXTENSION: 'readonly',
                STRUCTURE_ROAD: 'readonly',
                STRUCTURE_WALL: 'readonly',
                STRUCTURE_RAMPART: 'readonly',
                STRUCTURE_KEEPER_LAIR: 'readonly',
                STRUCTURE_PORTAL: 'readonly',
                STRUCTURE_CONTROLLER: 'readonly',
                STRUCTURE_LINK: 'readonly',
                STRUCTURE_STORAGE: 'readonly',
                STRUCTURE_TOWER: 'readonly',
                STRUCTURE_OBSERVER: 'readonly',
                STRUCTURE_POWER_BANK: 'readonly',
                STRUCTURE_POWER_SPAWN: 'readonly',
                STRUCTURE_EXTRACTOR: 'readonly',
                STRUCTURE_LAB: 'readonly',
                STRUCTURE_TERMINAL: 'readonly',
                STRUCTURE_CONTAINER: 'readonly',
                STRUCTURE_NUKER: 'readonly',
                STRUCTURE_FACTORY: 'readonly',
                STRUCTURE_INVADER_CORE: 'readonly',
                OK: 'readonly',
                ERR_NOT_OWNER: 'readonly',
                ERR_NO_PATH: 'readonly',
                ERR_NAME_EXISTS: 'readonly',
                ERR_BUSY: 'readonly',
                ERR_NOT_FOUND: 'readonly',
                ERR_NOT_ENOUGH_ENERGY: 'readonly',
                ERR_NOT_ENOUGH_RESOURCES: 'readonly',
                ERR_INVALID_TARGET: 'readonly',
                ERR_FULL: 'readonly',
                ERR_NOT_IN_RANGE: 'readonly',
                ERR_INVALID_ARGS: 'readonly',
                ERR_TIRED: 'readonly',
                ERR_NO_BODYPART: 'readonly',
                ERR_NOT_ENOUGH_EXTENSIONS: 'readonly',
                ERR_RCL_NOT_ENOUGH: 'readonly',
                ERR_GCL_NOT_ENOUGH: 'readonly',
                RESOURCE_ENERGY: 'readonly',
                RESOURCE_POWER: 'readonly',
                ATTACK: 'readonly',
                RANGED_ATTACK: 'readonly',
                WORK: 'readonly',
                MOVE: 'readonly',
                CARRY: 'readonly',
                HEAL: 'readonly',
                TOUGH: 'readonly',
                CLAIM: 'readonly',
                TERRAIN_MASK_WALL: 'readonly',
                TERRAIN_MASK_SWAMP: 'readonly',
                LOOK_STRUCTURES: 'readonly',
                LOOK_CONSTRUCTION_SITES: 'readonly',
                LOOK_AT: 'readonly',
                CONTROLLER_STRUCTURES: 'readonly',
            },
        },
    },
];
