/** @type {import('jest').Config} */
export default {
    testEnvironment: 'node',
    transform: {
        '^.+\\.js$': 'babel-jest',
    },
    transformIgnorePatterns: ['/node_modules/(?!(lodash)/)'],
    collectCoverageFrom: [
        'src/**/*.js',
        '*.js',
        '!jest.config.js',
        '!jest.config.mjs',
        '!node_modules/**',
        '!coverage/**',
    ],
    coverageReporters: ['lcov', 'text', 'json-summary'],
    coverageDirectory: 'coverage',
    testMatch: ['**/__tests__/**/*.js', '**/*.test.js', '**/*.spec.js'],
    reporters: [
        'default',
        [
            'jest-junit',
            {
                outputDirectory: 'test-results',
                outputName: 'junit.xml',
                classNameTemplate: '{filepath}',
            },
        ],
    ],
    globals: {},
    testPathIgnorePatterns: [
        '/node_modules/',
        'tests/roomManager.test.js',
        'tests/deploy.test.js',
        'tests/utils.emotions.test.js',
        'tests/security.emotions.test.js',
        'tests/utils.tasks.test.js',
        'tests/security.robust_init.test.js',
        'tests/sentinel_path_redaction.test.js',
        'tests/sentinel_logging.test.js',
        'tests/utils.logging.test.js',
        'tests/security.aggregation.test.js',
        'tests/main.test.js',
        'tests/memory.visualizer.test.js',
        'tests/security.dos.test.js',
        'tests/security.memory_map.test.js',
        'tests/system.adaptive.test.js',
        'tests/security.gamification.test.js',
        'tests/role.harvester.test.js',
        'tests/taskManager.test.js',
    ],
    modulePaths: ['<rootDir>'],
};
