import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create-nx-next",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <svg
          aria-hidden="true"
          style={{ display: "none" }}
          xmlns="http://www.w3.org/2000/svg"
        >
          <symbol id="favicon" viewBox="0 0 32 32">
            <rect width="32" height="32" fill="#000" />
          </symbol>
        </svg>
        {children}
      </body>
    </html>
  );
}