sonar.projectKey=tadanobutubutu_screeps
sonar.organization=tadanobutubutu

sonar.projectName=screeps
sonar.projectVersion=1.0

# Only scan the dummy placeholder directory to pass Quality Gate
sonar.sources=sonar-scan-target
sonar.exclusions=node_modules/**,coverage/**
sonar.tests=
sonar.test.inclusions=

sonar.sourceEncoding=UTF-8
