with open("scripts/ai_issue_solver.py", "r") as f:
    content = f.read()

content = content.replace(
    'test_note = (\n        f"Tests passed via **{winning_name}**."\n        if winning_name\n        else "No model passed tests -- manual review may be needed."\n    )',
    'test_note = (\n        f"Syntax check passed via **{winning_name}**."\n        if winning_name\n        else "No model passed syntax check -- manual review may be needed."\n    )'
)

content = content.replace(
    'pr_body = (\n        f"Closes #{issue_no}\\n\\n"\n        f"## Multi-Agent Fix\\n\\n"\n        f"This PR was generated by querying **all available free LLM APIs simultaneously** "\n        f"(Pollinations, Kilo Gateway, OVH Anonymous, Puter.js, HuggingFace, AI Horde, Gemini, OpenRouter).\\n\\n"\n        f"{test_note}\\n\\n"\n        f"Self-refinement loops used: up to {MAX_ATTEMPTS}."\n    )',
    'pr_body = (\n        f"Closes #{issue_no}\\n\\n"\n        f"## Multi-Agent Fix\\n\\n"\n        f"This PR was generated by querying **all available free LLM APIs simultaneously** "\n        f"(Pollinations, Kilo Gateway, OVH Anonymous, Puter.js, HuggingFace, AI Horde, Gemini, OpenRouter).\\n\\n"\n        f"{test_note}\\n\\n"\n        f"**Security Note:** For safety, the AI issue solver no longer executes untrusted code locally. It only performs syntax validation.\\n"\n        f"Please review the PR and let GitHub Actions run the full test suite in a sandboxed environment.\\n\\n"\n        f"Self-refinement loops used: up to {MAX_ATTEMPTS}."\n    )'
)

# Fix prompt as well since it mentions test suite
content = content.replace(
    'f"You are a JavaScript expert. Previous attempts to fix this issue failed the test suite.\\n"',
    'f"You are a JavaScript expert. Previous attempts to fix this issue failed the syntax check.\\n"'
)
content = content.replace(
    'f"Fix the test failures shown above.\\n"',
    'f"Fix the syntax errors shown above.\\n"'
)
content = content.replace(
    'print(\n                f"\\nAll {len(failures)} candidates failed tests. Feeding errors back into next attempt..."\n            )',
    'print(\n                f"\\nAll {len(failures)} candidates failed syntax check. Feeding errors back into next attempt..."\n            )'
)
content = content.replace(
    'print(f"\\nNo candidate passed tests after {MAX_ATTEMPTS} attempts.")',
    'print(f"\\nNo candidate passed syntax check after {MAX_ATTEMPTS} attempts.")'
)
content = content.replace(
    'f"The repository uses Jest for testing. Existing tests in /tests/ must continue to pass.\\n\\n"',
    'f"The repository uses Jest for testing. Existing tests in /tests/ must continue to pass. (The code will only be syntax-checked locally)\\n\\n"'
)
content = content.replace(
    'f"The repository uses Jest. Existing tests must continue to pass.\\n\\n"',
    'f"The repository uses Jest. Existing tests must continue to pass. (The code will only be syntax-checked locally)\\n\\n"'
)

with open("scripts/ai_issue_solver.py", "w") as f:
    f.write(content)
