version: 2.1
jobs:
  build_and_test:
    docker:
      - image: cimg/node:20.11.0
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: npm install -g pnpm
      - run:
          name: Install Dependencies
          command: pnpm install --frozen-lockfile
      - run:
          name: Run Linter
          command: pnpm run lint
      - run:
          name: Run Tests
          command: pnpm run test

workflows:
  version: 2
  screeps_pipeline:
    jobs:
      - build_and_test
