name: Deploy to Screeps PTR
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm install
      - run: npm run build
      - name: Deploy
        env:
          SCREEPS_TOKEN: ${{ secrets.SCREEPS_TOKEN }}
        run: npx screeps-api push --ptr